name: Nuget Deploy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, Pack and Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore CommonCode/CommonCode.sln

      - name: Build projects
        run: dotnet build CommonCode/CommonCode.sln --configuration Release

      - name: Pack all projects
        run: dotnet pack CommonCode/CommonCode.sln --configuration Release --no-build -o ./artifacts

      - name: Push packages to NuGet
        run: .github\scripts\push-packages.cmd
        shell: cmd
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}